name: Snaps

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref_name }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - .github/workflows/snaps.yml
    - bin/process_snaps.py

permissions: {}

jobs:
  ProcessSnaps:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: '3.14'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e  # v4.1.0

    - name: Install Snap dependencies
      run: |
        sudo snap install review-tools

    - name: Set up Launchpad credentials
      uses: DamianReeves/write-file-action@6929a9a6d1807689191dcc8bbe62b54d70a32b42  # v1.3
      with:
        path: lp_credentials
        contents: ${{ secrets.LAUNCHPAD_CREDENTIALS }}

    - name: Check for USNs and refresh snaps
      run: bin/process_snaps.py lp_credentials
