name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - .github/workflows/snap.yml
    - mir-ci/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref_name }}
  cancel-in-progress: true

jobs:
  arches:
    runs-on: ubuntu-latest
    outputs:
      arches: ${{ steps.get-arches.outputs.arches }}

    steps:
    - id: get-arches
      name: Determine which architectures to build for
      run: |
        ARCHES=( amd64 )
        if ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}; then
          ARCHES+=( armhf arm64 )
        fi
        jq --compact-output --null-input '$ARGS.positional' --args -- "${ARCHES[@]}" | awk '{ print "arches=" $0 }' >> $GITHUB_OUTPUT

  checkbox-mir:
    needs: [arches]
    runs-on: ubuntu-latest

    timeout-minutes: 360

    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJSON(needs.arches.outputs.arches) }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        repository: MirServer/checkbox-mir

    - name: Use the current mir-ci commit
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.parts.mir-ci.source-commit="${{ github.sha }}"' snap/snapcraft.yaml

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@release
      with:
        architecture: ${{ matrix.architecture }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        launchpad-credentials: ${{ secrets.LAUNCHPAD_CREDENTIALS }}
        launchpad-accept-public-upload: true
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/mir-ci-pr${{ github.event.number }}
