name: Snaps

on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'

jobs:
  ProcessSnaps:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Install Snap dependencies
      run: |
        sudo snap install review-tools

    - name: Set up Launchpad credentials
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: lp_credentials
        contents: ${{ secrets.LAUNCHPAD_CREDENTIALS }}

    - name: Check for USNs and refresh snaps
      run: bin/process_snaps.py lp_credentials
