name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - .github/workflows/snap.yml
    - mir-ci/**

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref_name }}
  cancel-in-progress: true

jobs:
  arches:
    runs-on: ubuntu-24.04
    permissions: {}
    outputs:
      arches: ${{ steps.get-arches.outputs.arches }}

    steps:
    - id: get-arches
      name: Determine which architectures to build for
      run: |
        ARCHES=( amd64 )
        if ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}; then
          ARCHES+=( armhf arm64 )
        fi
        jq --compact-output --null-input '$ARGS.positional' --args -- "${ARCHES[@]}" | awk '{ print "arches=" $0 }' >> "$GITHUB_OUTPUT"

  checkbox-mir:
    needs: [arches]
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    timeout-minutes: 360

    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJSON(needs.arches.outputs.arches) }}

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        repository: canonical/checkbox-mir
        fetch-depth: 0
        persist-credentials: false

    - name: Use the current mir-ci commit
      uses: mikefarah/yq@5a7e72a743649b1b3a47d1a1d8214f3453173c51  # v4.52.4
      with:
        cmd: yq -i '.parts.mir-ci.source-commit="${{ github.sha }}"' snap/snapcraft.yaml

    - name: Disable LFS for remote-build pushes
      run: |
        git lfs uninstall

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@bd56f0f0934af9edbbd49378645727d7ef7a4571  # release @ 2025.06.05
      with:
        architecture: ${{ matrix.architecture }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        launchpad-credentials: ${{ secrets.LAUNCHPAD_CREDENTIALS }}
        launchpad-accept-public-upload: true
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/mir-ci-pr${{ github.event.number }}
