name: Snaps

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref_name }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - .github/workflows/snaps.yml
    - bin/process_snaps.py

jobs:
  ProcessSnaps:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      uses: insightengineering/pip-action@v2
      with:
        requirements: requirements.txt

    - name: Install Snap dependencies
      run: |
        sudo snap install review-tools --edge

    - name: Set up Launchpad credentials
      uses: DamianReeves/write-file-action@v1.3
      with:
        path: lp_credentials
        contents: ${{ secrets.LAUNCHPAD_CREDENTIALS }}

    - name: Check for USNs and refresh snaps
      run: bin/process_snaps.py lp_credentials
