name: Test Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  TestReport:
    runs-on: ubuntu-latest
    steps:
    - name: Download the test results
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        name: test-results

    - name: Report test results
      uses: dorny/test-reporter@v1
      with:
        name: Test results
        path: 'test-results/**/junit-*.xml'
        reporter: java-junit
